# Generated by Django 3.0.2 on 2020-02-11 14:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_Name', models.TextField(max_length=200)),
                ('blog_Description', models.TextField(max_length=2000)),
                ('blog_status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('blog_date_created', models.DateTimeField(default=datetime.date.today, verbose_name='Blog Date Created')),
                ('blog_date_published', models.DateTimeField(auto_now=True, verbose_name='Blog Date Published')),
                ('blog_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-blog_date_created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=200)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblogapp.BlogEntry')),
            ],
        ),
    ]
